name: "Build One by One (anyone)"
on:
  workflow_dispatch:
    inputs:

      armbian_target:
        type: choice
        description: 'Build'
        required: false
        options:
        - kernel
        - build
        default: build

      armbian_kernel_branch:
        type: choice
        description: 'Kernel branch'
        options:
        - legacy
        - current
        - edge
        - vendor
        default: 'vendor'

      armbian_release:
        type: choice
        description: 'Userspace'
        options:
        - jammy
        - mantic
        - bookworm
        - trixie
        - sid
        default: 'bookworm'

      armbian_ui:
        type: choice
        description: 'User interface (not all works)'
        options:
        - minimal
        - server
        - xfce
        - gnome
        - cinnamon
        - i3-wm
        - kde-plasma
        default: 'server'

      armbian_version:
        description: 'Version'
        required: false
        default: ''

      armbian_board:
        type: choice
        description: 'Board'
        options:
        - som3588-cat

jobs:

  prepare_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDD-HHmm'
      - name: Create empty release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.time.outputs.time }}
          body_path: README.md
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: main
          draft: false
    outputs:
      release_id: ${{ steps.release.outputs.id }}

  build:
    name: "Build Armbian"
    runs-on: ubuntu-latest
    steps:
      - name: Check Pre Sources
        shell: bash
        run: |
          DEL_PATH=$(pwd)
          cd .. && rm -rf ${DEL_PATH}
          mkdir ${DEL_PATH} && cd ${DEL_PATH}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload Armbian image
        uses: YANXIAOXIH/SOM3588-Armbian@armbin
        if: matrix.DISTRO == 'armbian'
        with:
          armbian_token:              "${{secrets.GITHUB_TOKEN}}"
          armbian_target:             "${{inputs.armbian_target}}"
          armbian_release:            "${{inputs.armbian_release}}"
          armbian_kernel_branch:      "${{inputs.armbian_kernel_branch}}"
          armbian_ui:                 "${{inputs.armbian_ui}}"
          armbian_board:              "${{inputs.armbian_board}}"
          armbian_release_tittle:     "Armbian SDK"
          armbian_release_body:       "Virtual images for x86 and arm64"
          armbian_pgp_key:            "${{secrets.GPG_KEY1}}"
          armbian_pgp_password:       "${{secrets.GPG_PASSPHRASE1}}"
