name: Build-Armbian-test-0.1
on:  
  workflow_dispatch:  
    inputs:  
      BOARD:  
        description: 'Board type'  
        required: true 
        default: 'som3588-cat'
        type: choice
        options:
          - som3588-cat
      BRANCH:  
        description: 'Armbian branch'  
        default: 'vendor'  
        required: false 
        type: choice 
        options:
          - vendor
          - edge
      RELEASE:  
        description: 'Release name' 
        default: 'bookworm'
        required: true  
        type: choice
        options:
          - jammy
          - mantic
          - bookworm
          - trixie
          - noble
          - bullseye
      Version:
        description: 'Armbian Version'
        default: 'main'
        required: false 
        type: choice
        options: 
          - main
          - v24.11
          - v24.08
          - rk3588-6.12-initial
      BUILD_DESKTOP:  
        description: 'Build desktop environment'  
        default: 'no'  
        required: false  
        type: choice
        options:
          - no
          - yes
      COMPRESS_OUTPUTIMAGE:  
        description: 'Compress output image'  
        default: 'sha,xz'  
        required: false  
        type: string  
      BOOT_LOGO:  
        description: 'Include boot logo'  
        default: 'yes'  
        required: false  
        type: choice 
        options:
          - yes
          - no
env:
  TZ: Asia/Shanghai

jobs:  
  build-armbian:  
    runs-on: ubuntu-latest  
    steps:
      - name: SOM3588Cat-addboard
        uses: actions/checkout@v4
        with:
          repository: YANXIAOXIH/SOM3588-cat-armbian
          ref: main
          path: SOM3588Cat
          
      - name: armbian-build
        uses: actions/checkout@v4
        with:
          repository: armbian/build
          ref: main
          path: build
          
      - name: Compile Armbian
        shell: bash
        run: |
          cd ./build
          touch .ignore_changes
          
          git status
          docker pull ghcr.io/armbian/docker-armbian-build:armbian-ubuntu-jammy-latest
               
          ./compile.sh \
          BOARD=${{ inputs.BOARD }} \
          BRANCH=${{ inputs.BRANCH }} \
          RELEASE=${{ inputs.RELEASE }} \
          BUILD_MINIMAL=no \
          BUILD_DESKTOP=no \
          KERNEL_CONFIGURE=no \
          EXPERT=yes \
          BOARD_FIRMWARE_INSTALL="-full" \
          SHARE_LOG=no \
          USE_CCACHE=yes \
          DEBUG=yes \
          VENDOR=Armbian \
          COMPRESS_OUTPUTIMAGE=sha,gpg,xz
      - name: Prepare Release Metadata
        run: |  
          # 提取版本号
          # latest_image=$(ls ${{ github.workspace }}/build/output/images/Armbian-unofficial_*.img.xz | grep -oE 'Armbian-unofficial_[0-9.]+_.*' | sort -V | tail -n 1) 
          latest_image=$(ls ${{ github.workspace }}/build/output/images/Armbian*.img.xz | sort -V | tail -n 1)
          version=$(echo "$latest_image" | cut -d'_' -f2)  
  
          # 将版本号设置为环境变量  
          echo "VERSION=$version" >> $GITHUB_ENV
        
      - name: Upload image to Release  
        if: success() 
        uses: ncipollo/release-action@main
        with:  
          tag: "Armbian_${{ github.event.inputs.Version }}_${{ env.CURRENT_YEAR_MONTH }}"  
          name: "Armbian_${{ github.event.inputs.Version }}_${{ env.CURRENT_YEAR_MONTH }}"  
          artifacts: "${{ github.workspace }}/build/output/images/*"  
          allowUpdates: true 
          removeArtifacts: false 
          replacesArtifacts: true 
          token: ${{ secrets.GITHUB_TOKEN }}  
          body: |  
            ### Armbian Image Information  
            - Release: ${{ github.event.inputs.RELEASE }}    
            - Version: ${{ env.VERSION }}  
            ### Armbian Image Verification  
            - sha256sum   
          draft: false  
          prerelease: false  
