name: Build-som3588-cat-OS
on:
  workflow_dispatch:

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDD-HHmm'
    outputs:
      release_id: ${{ steps.release.outputs.id }}
  build:
    runs-on: ubuntu-latest
    needs: prepare_release
    strategy:
      matrix:
        BOARD: [som3588-cat]
        DISTRO: [armbian]
        FLAVOR: [debian]
        BRANCH: [vendor]
    steps:
      - name: Check Pre Sources
        shell: bash
        run: |
          DEL_PATH=$(pwd)
          cd .. && rm -rf ${DEL_PATH}
          mkdir ${DEL_PATH} && cd ${DEL_PATH}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload Armbian image
        uses: YANXIAOXIH/SOM3588-Armbian@main
        if: matrix.DISTRO == 'armbian'
        with:
          branch: ${{ matrix.BRANCH }}
          board: ${{ matrix.BOARD }}
          flavor: ${{ matrix.FLAVOR }}
          release-id: ${{ needs.prepare_release.outputs.release_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
